### PR TITLE
Move completely to go15

### PR DESCRIPTION
**Pull request by cgclever**
For context, see https://clever.atlassian.net/browse/INFRA-1112 

This PR was autogenerated. @schimmy  you were chosen as the most active commiter of this repo, please review and check that builds still pass.   
Some known, but difficult to automate, errors are: 
  * In the Makefile and test_drone.sh, performing `go get` on the repo while it's now only necessary for packages such as errcheck or lint. 
  * Makefile testing vendored dependencies (which in turn tries to compile them, oftentimes creating import errors).

  * Dependencies aren't compatible with go1.5. For example appasaurus ran into this with gopkg.in/mgo.v2 (the solution here is to run `go get -u gopkg.in/mgo.v2`). 

If there are any problems, feel free to ping @cgclever for troubleshooting. 

For understanding Godeps and vendoring see [this doc](https://docs.google.com/document/d/1YZg2S7v1bir3MG1YvswAD2Y0KrsuDr-NCr6pPG2ycEM/edit#). 

Thank you\!

### CODE REVIEW

**Comment by xavi-** [comment]
I am not familiar with this repo.  Not sure if I'm the person best to review and fix the build error.

**Comment by xavi-** [comment]
Tried reverting to older commits to find a time when tests passed, but no luck.  Assigning to @rgarcia since he's higher up on contribution list.

**Comment by rgarcia** [comment]
@cgclever @xavi- mgotail is a library, so it should *not* vendor dependencies. I hope this we didn't introduce this in other library repos. Assigning to @cgclever to fix.

**Comment by cgclever** [comment]
@rgarcia @xavi- is it reasonable to include a glide.yaml? For certain repos to pass their tests they need versioning and glide might be the best solution here. It may also be a worthwhile record keeping tool for anyone who wants insight into a libraries specific dependencies.

**Comment by rgarcia** [comment]
If a library truly only works with a certain version of a dependency, or needs a patched version of a dependency, the convention (I think) is to literally copy that dependency tree into a non-vendored sub-package (re-writing imports as necessary). That's the only way to ensure that consumers of the library use the correct code.

Vendoring will get the tests to pass, but kind of sweeps the problem under the rug. It also creates the appearance that a library uses a specific version of a dependency, which is not the case.

In the case of this repo, even vendoring does not seem to make the tests pass. I made a branch that does some hacky vendoring (simple call to `git checkout` in the one dependency of this repo, mgo), and tests are still failing: https://github.com/Clever/mgotail/compare/tests. Thus, I think further investment should dig into getting the tests to pass on this branch. Perhaps @ericavonb can take a look as the original author.

**Comment by rgarcia** [comment]
got things working in https://github.com/Clever/mgotail/pull/8

**Pull request closed without merging**
